name: Deploy to Docker
on:
  push:
    branches: ["master"]

env:
  DOCKER_HOST: tcp://172.20.0.2:2375

jobs:
  build-and-deploy:
    runs-on: docker
    container:
      image: node:20-alpine
    steps:
      # Устанавливаем Docker CLI
      - name: Install Docker CLI
        run: |
          apk add --no-cache docker-cli

      # Получаем исходный код из репозитория
      - name: Checkout code
        uses: actions/checkout@v4

      # Собираем Docker-образ
      - name: Build Docker image
        run: |
          echo "DOCKER_HOST: $DOCKER_HOST"
          docker build \
            -t discord-bot .

      # Перезапуск контейнера
      - run: |
          docker stop discord-bot || true
          docker rm discord-bot || true
          docker run -d \
            --name discord-bot \
            --restart unless-stopped \
            -e BOT_NAME=${{ secrets.BOT_NAME }} \
            -e DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }} \
            -e OAUTH_CLIENT_ID=${{ secrets.OAUTH_CLIENT_ID }} \
            -e OPENROUTER_KEY=${{ secrets.OPENROUTER_KEY }} \
            -e YOUTUBE_TOKEN=${{ secrets.YOUTUBE_TOKEN }} \
            discord-bot
